---
- name: provision
  hosts: thinkpad
  roles:
    - role: packages_base
      sudo: yes
      tags:
        - packages

    - role: jemalloc
      sudo: yes
      jemalloc_install: source
      tags:
        - packages

    - role: rvm1-ruby
      sudo: yes
      rvm1_rubies:
        - ruby-2.2.2
      rvm1_install_flags: --auto-dotfiles --user-install
      rvm1_ruby_install_flags: --with-jemalloc
      rvm1_install_path: "/home/{{ ansible_ssh_user }}/.rvm"
      rvm1_user: "{{ ansible_ssh_user }}"

    - role: virtualbox
      sudo: yes
      tags:
        - packages

    - role: nodejs
      sudo: yes
      tags:
        - packages

    - role: packages_custom
      sudo: yes
      tags:
        - packages

    - role: numix
      sudo: yes
      tags:
        - packages

    - role: dropbox
      sudo: yes

    - role: heroku
      sudo: yes

    - role: thinkfan
      sudo: yes

    - role: nuvola_player
      sudo: yes
      tags:
        - nuvola

    - role: vagrant
      sudo: yes
      tags:
        - vagrant

    - role: dotfiles
      tags:
        - dotfiles

    - role: system
      sudo: yes
      tags:
        - system

    - role: cleanup
      sudo: yes
