---
- name: update packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: upgrade packages
  apt:
    upgrade: dist

- name: install new packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - tmux
    - software-properties-common
    - python-software-properties
    - htop
    - speedcrunch
    - redshift
    - aptitude

