---
- name: generate conf
  shell: ./autogen.sh
  args:
    chdir: "{{ nemo_extensions_dropbox_src_dir }}"

- name: config dropbox
  shell: ./configure
  args:
    chdir: "{{ nemo_extensions_dropbox_src_dir }}"

- name: make
  shell: make
  args:
    chdir: "{{ nemo_extensions_dropbox_src_dir }}"

- name: make install
  shell: make install
  args:
    chdir: "{{ nemo_extensions_dropbox_src_dir }}"
