---
- name: add virtualbox apt key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: add virtualbox apt repo
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present

- name: install virtualbox
  apt:
    name: "virtualbox-{{ virtualbox_version }}"
    state: "{{ virtualbox_install_state | default('present') }}"
    update_cache: yes
    cache_valid_time: 3600
