---
- name: create tmp dir
  file:
    state: directory
    path: "{{ dropbox_tmp_dir }}"

- name: download dropbox
  get_url:
    url: "{{ dropbox_url }}"
    dest: "{{ dropbox_tmp_dir }}/dropbox.deb"
  register: dropbox_deb

- name: install dropbox
  apt:
    deb: "{{ dropbox_deb.dest }}"

- name: clean up tmp dropbox deb
  file:
    state: absent
    path: "{{ dropbox_deb.dest }}"
