---
- name: add heroku key
  apt_key:
    url: https://toolbelt.heroku.com/apt/release.key
    state: present

- name: add heroku apt repo
  apt_repository:
    repo: "deb http://toolbelt.heroku.com/ubuntu ./"
    state: present

- name: install heroku packages
  apt:
    state: "{{ heroku_install_state | default('present') }}"
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items: heroku_packages_to_install
