---
- name: add multiarch
  command: dpkg --add-architecture i386

- name: add nuvola repository
  apt_repository:
    repo: ppa:nuvola-player-builders/stable

- name: apt-get upgrade
  apt:
    upgrade: dist

- name: install nuvola player
  apt:
    name: nuvolaplayer
    state: "{{ nuvola_install_state | default('present') }}"
    update_cache: yes
    cache_valid_time: 3600
