---
- name: add multiarch (nuvola 2)
  command: dpkg --add-architecture i386

- name: add nuvola repository (nuvola 2)
  apt_repository:
    repo: ppa:nuvola-player-builders/unstable

- name: apt-get upgrade (nuvola 2)
  apt:
    upgrade: dist

- name: install nuvola player (nuvola 2)
  apt:
    name: nuvolaplayer
    state: "{{ nuvola_install_state | default('present') }}"
    update_cache: yes
    cache_valid_time: 3600
