---
system_configs:
  - src: etc/sysctl.d/10-vm-swappiness.conf.j2
    dest: /etc/sysctl.d/10-vm-swappiness.conf
    mode: "u=rw,g=r,o=r"

  - src: etc/rc.local.j2
    dest: /etc/rc.local
    mode: "u=rwx,g=xr,o=x"

  - src: etc/security/limits.d/60-file-limit.conf.j2
    dest: /etc/security/limits.d/60-file-limit.conf
    mode: "u=rw,g=r,o=r"

system_file_limit: 16384
